options:
  SERVER_NAME: "8Core"
  SERVER_DOMAIN: "example.com"
  SERVER_STORE_DOMAIN: "example.com/store"
  SERVER_APPEAL_DOMAIN: "example.com/appeal"
  SERVER_DISCORD_LINK: "https://example.com/discord"
