# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Core Grant execute permission for gradlew
      run: chmod +x Core/gradlew
    - name: Core Build with Gradle
      run: Core/gradlew Core:shadowJar
    - name: Bungee Grant execute permission for gradlew
      run: chmod +x BungeeProxy/gradlew
    - name: Bungee Build with Gradle
      run: BungeeProxy/gradlew BungeeProxy:shadowJar
